### PR TITLE
Fix (*)

### PR DESCRIPTION
**Pull request by atilkan**
fix(*): improve compatibility with semi-colon before global IIFE

### CODE REVIEW

**Comment by jlmakes** [comment]
@atilkan Thanks!

Can you update the commit message to `fix(*): improve compatibility with semi-colon before IIFE'? I’ll merge this in after! :bow:

**Comment by atilkan** [comment]
done.

**Comment by jlmakes** [comment]
Hmm, you updated the pull request message. What I mean is to run:
```
git commit --amend -m 'fix(*): improve compatibility with semi-colon before global IIFE'
```
Thanks @atilkan

**Comment by atilkan** [comment]
I made it on website and can't change the commit message. Still learning git.

**Comment by jlmakes** [comment]
Squashed and merged. Thanks!

**Pull request closed without merging**
