### PR TITLE
grammar in comments

### PR DESCRIPTION
**Pull request by jacobhamblin**
Just the classic contraction vs possession deal

### CODE REVIEW

**Comment by jlmakes** [comment]
Haha, this is what you get for staying up 30 hours straight…

Thanks @jacobhamblin :bow:

**Comment by jlmakes** [comment]
Haha, this is what you get for staying up 30 hours straight…

Can you:
- `git commit --amend -m "cleanup(*): typos"` 
- `git push origin master -f`

Thanks @jacobhamblin :bow:

**Comment by jacobhamblin** [comment]
Sure! It should reflect the amend now.

**Comment by jlmakes** [comment]
@jacobhamblin Thanks!

**Pull request merged**
