### PR TITLE
ScrollReveal v3.0.0

### PR DESCRIPTION
**Pull request by jlmakes**
screen shot 2015-08-18 at 12 05 05 pm

***

[scrollReveal version](http://scrollrevealjs.org) [Release Candidate](http://opensource.org/licenses/MIT)

### CODE REVIEW

**Comment by jlmakes** [comment]
Hmm, actually looks like there’s a little more to do to support multiple `sr.reveal()` calls on the same element set...

**Comment by jlmakes** [comment]
#### Refactored Callback

The old callback (ie. `config.complete`) was unreliable, and was only available to non-resetting elements. This was an oversight, as `reset` is a popular feature of ScrollReveal and callbacks are a valuable and commonly leveraged, so...

- `config.complete` *has been removed.*
- `config.afterReveal` has been **added**.
- `config.afterReset` has been **added**.

#### afterReveal

As you might guess, this callback fires after any reveal animation completes. This means whether the element reveals only once, or multiple times (due to resets), you will have access to `afterReveal`.

*Sample Usage*
```js
myRevealCallback = function( domEl ){
  console.log("Reveal complete!");
}

window.sr = new scrollReveal({ afterReveal: myRevealCallback });
```
>**Note:** ScrollReveal will pass the affected DOM element as the first parameter. Keep this in mind when defining your callback functions.

#### afterReset

As you might guess, this callback fires after every animation reset.

*Sample Usage*
```js
myResetCallback = function( domEl ){
  console.log("Animation has reset!");
}

window.sr = new scrollReveal({
  reset:       true,
  afterResetl: myRevealCallback
});
```

#### Timing

I’ve made sure that if you interrupt an animation or reset that's in progress, no callbacks will fire, and the remaining time on the animation will factor into any future callbacks. In other words, your callbacks should fire on time... every time. :sunglasses:

**Comment by jlmakes** [comment]
#### Release

ScrollReveal v3.0.0-RC is complete, pending a last round of tests and feedback. As soon as the new demo and documentation are ready, ScrollReveal 3 goes gold! :sparkles: 

**Expected launch:** Monday, September 21

**Comment by cppraikcp** [comment]
ohk then send me your link

**Comment by jlmakes** [comment]
scrollreveal-phoenix

**Comment by jlmakes** [comment]
After long last....

**Pull request merged**
