### PR TITLE
Fix selector with config.container in Instantiation [fix #289]

### LINKED ISSUE #289: Selector not working with config.container in Instantiation
Seems like ScrollReveal is failing to recognize selectors when overriding defaults during instantiation.

_Selector as `config.container` for instantiation (broken):_
```js
var sr = new ScrollReveal({ container: '.main' });
sr.reveal('.child');
```
[JSBin Demo](https://jsfiddle.net/68hrp3hk/)

***

_DOM Node as `config.container` for instantiation (works):_
```js
var sr = new ScrollReveal({ container: document.querySelector('.main') });
sr.reveal('.child');
```
[JSBin Demo](https://jsfiddle.net/L4gvhrnw/)

***

_Selector as `config.container` for reveal (works):_
```js
var sr = new ScrollReveal();
sr.reveal('.child', { container: '.main' });
```
[JSBin Demo](https://jsfiddle.net/dmp5pz3s/)

### PR DESCRIPTION
**Pull request by jumbosushi**
Save container as Node object when the config input is string

### CODE REVIEW

**Comment by jlmakes** [comment]
Good catch @jumbosushi and thanks for the PR.

I think we would do better if the `_resolveContainer()` method simply returned the correct value, rather than setting outside variables (such as `sr.defaults.container`).

How about if we instead revert this change, but use your idea on [Line 44](https://github.com/jlmakes/scrollreveal.js/blob/master/src/scrollreveal.js#L44):

```diff
 if (sr.isSupported()) {
   sr.tools.extend(sr.defaults, config || {})

-  _resolveContainer(sr.defaults)
+  sr.defaults.container = _resolveContainer(sr.defaults)
```

**Comment by jumbosushi** [comment]
Sure! That's a better approach.

**Comment by jlmakes** [comment]
I just noticed this change was done to the unminified distribution only, and not in the the minified distribution or the source.

I fumbled with the timeline a little bit, but I put this change into the source and built a new distribution. I also updated the README and bumped everything to `v3.3.2`.

Thanks @jumbosushi!

**Comment by jumbosushi** [comment]
Yessss! Thanks for publishing it so quickly!
Let me know if you need hands with any other issues and I can gladly help 💪

**Pull request merged**
